"use client";
import { readValidatedResponse, sessionResponseSchema, apiErrorSchema } from "@/lib/api-response";
import { useState } from "react";
import { useRouter } from "next/navigation";
export function SessionControls({sessionId,status,availableMinutes,adaptive=false}:{sessionId?:string;status?:string;availableMinutes?:number;adaptive?:boolean}){
  const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function send(action:"plan"|"start"|"complete"|"abandon",budgetMinutes?:number){setBusy(true);setError("");try{const response=await fetch("/api/study-sessions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...action==="plan"?{budgetMinutes}:{sessionId}})});if(!response.ok){const failure=apiErrorSchema.safeParse(await response.json());throw new Error(failure.success?failure.data.message??"Não foi possível atualizar a sessão.":"Resposta inválida do servidor.");}const body=await readValidatedResponse(response,sessionResponseSchema);router.push(`/study/${body.sessionId}`);router.refresh();}catch(error){setError(error instanceof Error?error.message:"Falha ao atualizar sessão.");}finally{setBusy(false);}}
  const minimum=adaptive?10:15;
  return <div className={sessionId?"learning-controls":adaptive?"time-options is-adaptive":"time-options"} aria-busy={busy}>{!sessionId?<>{adaptive?[10,20,30,45].map((minutes,index)=><button key={minutes} className={`time-option${index===0?" is-primary":""}`} disabled={busy||availableMinutes!==undefined&&availableMinutes<minutes} onClick={()=>void send("plan",minutes)}>{index===0?`Estudar ${minutes} min`:`${minutes} min`}</button>):<><button className="time-option is-primary" disabled={busy||availableMinutes!==undefined&&availableMinutes<15} onClick={()=>void send("plan",15)}>Estudar 15 min</button><button className="time-option" disabled={busy||availableMinutes!==undefined&&availableMinutes<30} onClick={()=>void send("plan",30)}>30 min</button><button className="time-option" disabled={busy||availableMinutes!==undefined&&availableMinutes<60} onClick={()=>void send("plan",60)}>{availableMinutes===undefined?"Sessão completa":"60 min"}</button></>}{availableMinutes!==undefined&&availableMinutes<minimum&&<p className="session-budget-note">{availableMinutes===0?"Não há tempo distribuído para uma nova sessão hoje. Confira sua rotina.":`Há ${availableMinutes} min disponíveis. Para preparar uma sessão, reserve pelo menos ${minimum} min na rotina.`}</p>}</>:status==="PLANNED"?<button className="primary-button" disabled={busy} onClick={()=>void send("start")}>Começar sessão</button>:status==="ACTIVE"?<><button className="primary-button" disabled={busy} onClick={()=>void send("complete")}>Concluir sessão</button><button className="secondary-button" disabled={busy} onClick={()=>void send("abandon")}>Encerrar sem concluir</button></>:null}{error&&<p role="alert">{error}</p>}</div>;
}
