"use client";
import { readValidatedResponse, sessionResponseSchema, apiErrorSchema } from "@/lib/api-response";
import { useState } from "react";
import { useRouter } from "next/navigation";
export function SessionControls({sessionId,status}:{sessionId?:string;status?:string}){
  const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function send(action:"plan"|"start"|"complete"|"abandon",budgetMinutes?:number){setBusy(true);setError("");try{const response=await fetch("/api/study-sessions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...action==="plan"?{budgetMinutes}:{sessionId}})});if(!response.ok){const failure=apiErrorSchema.safeParse(await response.json());throw new Error(failure.success?failure.data.message??"Não foi possível atualizar a sessão.":"Resposta inválida do servidor.");}const body=await readValidatedResponse(response,sessionResponseSchema);router.push(`/study/${body.sessionId}`);router.refresh();}catch(error){setError(error instanceof Error?error.message:"Falha ao atualizar sessão.");}finally{setBusy(false);}}
  return <div className={sessionId?"learning-controls":"time-options"} aria-busy={busy}>{!sessionId?<><button className="time-option is-primary" disabled={busy} onClick={()=>void send("plan",15)}>Estudar 15 min</button><button className="time-option" disabled={busy} onClick={()=>void send("plan",30)}>30 min</button><button className="time-option" disabled={busy} onClick={()=>void send("plan",60)}>Sessão completa</button></>:status==="PLANNED"?<button className="primary-button" disabled={busy} onClick={()=>void send("start")}>Começar sessão</button>:status==="ACTIVE"?<><button className="primary-button" disabled={busy} onClick={()=>void send("complete")}>Concluir sessão</button><button className="secondary-button" disabled={busy} onClick={()=>void send("abandon")}>Encerrar sem concluir</button></>:null}{error&&<p role="alert">{error}</p>}</div>;
}
