import { expect,test } from "@playwright/test";
import source from "../../packs/seeds/ifsc-2027.golden.track.v2.json";
import { trackPackV2Schema } from "@/features/import/application/track-pack-v2-schema";
import { questionSchema } from "@/features/questions/contracts";
test("navigates drafts, saves flags, resumes, reviews and finalizes through the existing EXAM engine",async({page,request},testInfo)=>{
  test.skip(process.env.FEATURE_REAL_EXAM!=="true","Enable real exam presentation.");test.setTimeout(90000);
  const pack=trackPackV2Schema.parse(source);pack.packId="estudisc.exam.navigation.fixture";pack.track.id="exam-navigation-fixture";
  const questions=["MAT","POR","CIE","GH"].flatMap(subjectCode=>Array.from({length:7},(_,index)=>{const base=pack.questions.find(q=>q.subjectCode===subjectCode)!;return questionSchema.parse({...base,id:`exam-nav-${subjectCode}-${index}`,type:"multiple_choice",status:"published",stem:`Questão local ${subjectCode} ${index+1}`,choices:Array.from({length:5},(_,option)=>({id:String(option),content:`Alternativa ${option+1}`,correct:option===0})),answer:{kind:"multiple_choice",choiceId:"0"},exposurePolicy:{...base.exposurePolicy,minimumDaysBetween:0}});}));
  pack.questions.push(...questions);expect((await request.post("/api/import/track",{data:pack})).ok()).toBe(true);
  const imported=await request.post("/api/admin/assessment-templates",{data:{id:"exam-navigation-template",version:1,title:"Prova local",kind:"FULL_SIMULATION",trackId:pack.track.id,durationMinutes:60,status:"published",items:questions.map(q=>({id:q.id,version:q.version}))}});expect(imported.ok(),await imported.text()).toBe(true);
  const template=await imported.json();const started=await request.post("/api/assessments",{data:{templateId:template.id,startKey:crypto.randomUUID()}});expect(started.ok()).toBe(true);const instance=await started.json();
  await page.goto(`/assessments/${instance.id}`);await expect(page.getByRole("navigation",{name:"Navegação das questões"})).toBeVisible();await expect(page.getByText("Tutor opcional",{exact:true})).toHaveCount(0);
  for(const width of [320,1280]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);await page.screenshot({path:testInfo.outputPath(`exam-active-${width}.png`)});}
  await page.getByRole("radio").first().check();await page.getByRole("checkbox",{name:"Revisar depois"}).check();await page.getByRole("button",{name:"Próxima questão",exact:true}).click();await page.getByRole("button",{name:"Questão anterior",exact:true}).click();await expect(page.getByRole("radio").first()).toBeChecked();await expect(page.getByRole("checkbox",{name:"Revisar depois"})).toBeChecked();
  await page.getByRole("button",{name:"Conferir simulado",exact:true}).click();await expect(page.getByRole("button",{name:"Finalizar simulado",exact:true})).toBeDisabled();await page.getByRole("button",{name:"Ver questão 1",exact:true}).click();await page.getByRole("button",{name:"Salvar resposta",exact:true}).click();await expect(page.getByRole("status").filter({hasText:"Resposta salva"})).toBeVisible();
  await page.reload();await expect(page.getByRole("radio").first()).toBeChecked();await expect(page.getByRole("checkbox",{name:"Revisar depois"})).toBeChecked();await page.getByRole("button",{name:"Conferir simulado",exact:true}).click();await expect(page.getByRole("region",{name:"Conferência final"})).toContainText("1 resposta salva");await page.getByRole("button",{name:"Finalizar simulado",exact:true}).click();await expect(page.getByRole("heading",{name:"Seu resultado",exact:true})).toBeVisible();await expect(page.getByRole("heading",{name:"Questões por conceito",exact:true})).toBeVisible();
  for(const width of [320,360,390,430,1280]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);if(width===320||width===1280)await page.screenshot({path:testInfo.outputPath(`exam-result-${width}.png`)});}
});
