import { expect, test } from "@playwright/test";
import { mkdirSync } from "node:fs";
import { join } from "node:path";
import { lessonVersionFixture } from "../fixtures/lesson-version-import";
test("imports one new lesson version through existing UI, keeps collection size and previews numeric exploration", async ({ page, request }, testInfo) => {
  const { context, packet } = lessonVersionFixture(true);
  expect((await request.post("/api/import/track", { data: context })).ok()).toBe(true);
  await page.goto("/import");
  await page.getByText("Importação avançada (JSON ou aula gerada por IA)", { exact: true }).click();
  await page.getByLabel("JSON do Track Pack").fill(JSON.stringify(packet));
  await page.getByRole("button", { name: "Preview", exact: true }).click();
  await expect(page.getByRole("status", { name: "Estado da importação" })).toContainText("Preview válido");
  await page.getByRole("button", { name: "Aplicar", exact: true }).click();
  await expect(page.getByRole("status", { name: "Versão da aula importada." })).toContainText("MAT-07 v5");
  const directory = join(process.cwd(), ".local/targeted-import-ui"); mkdirSync(directory, { recursive: true });
  await page.getByRole("status", { name: "Versão da aula importada." }).screenshot({ path: join(directory, `${testInfo.project.name}-import.png`) });
  await page.goto("/tracks/targeted-version-fixture");
  await expect(page.getByRole("link", { name: /Porcentagem/ })).toHaveCount(1);
  await page.goto("/lessons/MAT-07");
  await expect(page.getByText("Prévia administrativa · versão ainda não publicada.", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Ver tudo", exact: true }).click();
  const region = page.getByRole("region", { name: "Explore a porcentagem", exact: true });
  await expect(region.getByRole("status")).toHaveText("16% de 275 = 44");
  await region.getByRole("textbox", { name: "Valor base", exact: true }).fill("300");
  await region.getByRole("textbox", { name: "Porcentagem", exact: true }).fill("20");
  await expect(region.getByRole("status")).toHaveText("20% de 300 = 60");
  expect((await request.post("/api/import/lesson", { data: packet })).status()).toBe(200);
  const conflict = { ...packet, authorId: "different" };
  expect((await request.post("/api/import/lesson", { data: conflict })).status()).toBe(409);
  await page.goto("/lessons/MAT-07?version=4");
  await page.getByRole("button", { name: "Ver tudo", exact: true }).click();
  await expect(page.getByRole("region", { name: "Explore a porcentagem", exact: true })).toHaveCount(0);
  await page.setViewportSize({ width: 320, height: 900 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
});
