import { createHash } from "node:crypto";
import { getMemoryStore } from "./memory-store";
import { AssessmentStateError } from "./assessment-repository";
import { assessmentTemplateSchema,assessmentSnapshotSchema,ASSESSMENT_POLICY,validateAssessmentComposition } from "@/features/assessments/contracts";
import { scoreAssessment,assessmentFeedback,diagnosticSignals } from "@/features/assessments/scoring";
import { questionSchema } from "@/features/questions/contracts";
import { studentQuestion } from "@/features/questions/student-view";
import { hashCanonicalJson } from "@/lib/canonical-json";
import { evidenceStrengthV2,MASTERY_V2 } from "@/features/mastery/mastery-policy-v2";
import { REVIEW_V2 } from "@/features/review/review-policy-v2";
export class MemoryAssessmentRepository{
  constructor(private readonly store=getMemoryStore()){}
  private question(id:string,version:number){const input=this.store.packImports.flatMap(entry=>entry.manifest?.schema==="caderno.track.v2"?entry.manifest.questions:[]).find(question=>question.id===id&&question.version===version);if(!input)throw new AssessmentStateError();return questionSchema.parse(input);}
  async importTemplate(input:unknown){const definition=assessmentTemplateSchema.parse(input);validateAssessmentComposition(definition,definition.items.map(ref=>this.question(ref.id,ref.version)));const contentHash=hashCanonicalJson(definition);const existing=this.store.assessmentTemplates.find(row=>row.definition.id===definition.id&&row.definition.version===definition.version);if(existing){if(existing.contentHash!==contentHash)throw new Error("Assessment template version conflict");return existing;}const row={id:crypto.randomUUID(),definition,contentHash};this.store.assessmentTemplates.push(row);return row;}
  async listTemplates(){return this.store.assessmentTemplates.filter(row=>row.definition.status==="published").map(row=>({id:row.id,stableId:row.definition.id,version:row.definition.version,kind:row.definition.kind,definition:row.definition}));}
  async list(ownerId:string){return this.store.assessmentInstances.filter(row=>row.ownerId===ownerId).slice(-20).reverse().map(row=>({id:row.id,status:row.status,mode:row.snapshot.mode,startedAt:row.startedAt,deadlineAt:row.deadlineAt,result:row.result}));}
  async start(ownerId:string,templateId:string,startKey:string,now=new Date()){
    const existing=this.store.assessmentInstances.find(row=>row.ownerId===ownerId&&(row.startKey===startKey||row.status==="ACTIVE"));if(existing){if(existing.templateId!==templateId)throw new AssessmentStateError();return {id:existing.id};}
    const row=this.store.assessmentTemplates.find(row=>row.id===templateId);if(!row||row.definition.status!=="published"||row.definition.availableAt&&Date.parse(row.definition.availableAt)>now.getTime())throw new AssessmentStateError();
    const template=row.definition,id=crypto.randomUUID();
    const questions=template.items.map(ref=>{const question=this.question(ref.id,ref.version);const exposure=this.store.questionExposures.find(item=>item.ownerId===ownerId&&item.questionId===ref.id);if(!question.exposurePolicy.reservedForAssessment&&exposure&&now.getTime()-exposure.lastSeenAt.getTime()<question.exposurePolicy.minimumDaysBetween*86400000)throw new AssessmentStateError();const choiceOrder=(question.choices??[]).map(choice=>choice.id);if(template.shuffleChoices)choiceOrder.sort((a,b)=>createHash("sha256").update(`${id}:${ref.id}:${a}`).digest("hex").localeCompare(createHash("sha256").update(`${id}:${ref.id}:${b}`).digest("hex")));return {versionId:crypto.randomUUID(),question,choiceOrder};});
    validateAssessmentComposition(template,questions.map(item=>item.question),true);const mode=template.kind==="FULL_SIMULATION"||template.kind==="OFFICIAL_EXAM"?"EXAM":"ASSESSMENT";
    const snapshot=assessmentSnapshotSchema.parse({kind:template.kind,mode,questions,durationMinutes:template.durationMinutes,policyVersion:ASSESSMENT_POLICY,masteryPolicy:MASTERY_V2,reviewPolicy:REVIEW_V2});
    for(const item of questions){const exposure=this.store.questionExposures.find(row=>row.ownerId===ownerId&&row.questionId===item.question.id);if(exposure){exposure.timesSeen++;exposure.lastSeenAt=now;}else this.store.questionExposures.push({ownerId,questionId:item.question.id,lastSeenAt:now,timesSeen:1});}
    this.store.assessmentInstances.push({id,ownerId,templateId,startKey,status:"ACTIVE",snapshot,startedAt:now,deadlineAt:new Date(now.getTime()+template.durationMinutes*60000),finalizedAt:null,result:null});return {id};
  }
  async view(ownerId:string,id:string){const row=this.store.assessmentInstances.find(row=>row.id===id&&row.ownerId===ownerId);if(!row)return null;return {serverNow:Date.now(),id,status:row.status,mode:row.snapshot.mode,kind:row.snapshot.kind,startedAt:row.startedAt.toISOString(),deadlineAt:row.deadlineAt.toISOString(),questions:row.snapshot.questions.map(item=>{const question=studentQuestion(item.question);return {versionId:item.versionId,question:{...question,choices:question.choices?[...question.choices].sort((a,b)=>item.choiceOrder.indexOf(a.id)-item.choiceOrder.indexOf(b.id)):undefined}};}),responses:this.store.assessmentResponses.filter(response=>response.instanceId===id).map(response=>({versionId:response.versionId,response:response.response,flagged:response.flagged})),result:row.status==="FINALIZED"?row.result:null};}
  async save(ownerId:string,id:string,versionId:string,response:unknown,flagged:boolean,now=new Date()){const row=this.store.assessmentInstances.find(row=>row.id===id&&row.ownerId===ownerId);if(!row||row.status!=="ACTIVE"||now.getTime()>row.deadlineAt.getTime()||!row.snapshot.questions.some(item=>item.versionId===versionId))throw new AssessmentStateError();const existing=this.store.assessmentResponses.find(item=>item.instanceId===id&&item.versionId===versionId);if(existing){existing.response=response;existing.flagged=flagged;}else this.store.assessmentResponses.push({instanceId:id,versionId,response,flagged});return {saved:true};}
  async finalize(ownerId:string,id:string,now=new Date()){
    const row=this.store.assessmentInstances.find(row=>row.id===id&&row.ownerId===ownerId);if(!row)throw new AssessmentStateError();if(row.status==="FINALIZED")return row.result;if(row.status!=="ACTIVE")throw new AssessmentStateError();
    const scored=scoreAssessment(row.snapshot,new Map(this.store.assessmentResponses.filter(response=>response.instanceId===id).map(response=>[response.versionId,response.response])));
    for(const [index,item] of scored.items.entries()){
      const attemptId=crypto.randomUUID();this.store.attempts.push({id:attemptId,ownerId,activityStableId:`assessment:${id}:${item.question.id}`,attemptNumber:index+1,outcome:item.evaluation.outcome,source:JSON.stringify(item.response),response:item.response,submissionKey:`assessment:${id}:${item.versionId}`,questionVersionId:item.versionId,context:{assessmentId:id,mode:row.snapshot.mode},createdAt:now,tests:[],output:{status:"completed",stdout:[],stderr:[],result:null,runtimeVersion:"question.v1",limits:{timeoutMs:0,outputLimit:0},capabilities:{dom:false,network:false,ambientSecrets:false}}});
      if(!item.evaluation.evidenceEligible)continue;
      for(const conceptStableId of item.question.conceptIds){const history=this.store.conceptEvidence.filter(event=>event.ownerId===ownerId&&event.conceptStableId===conceptStableId);const delayedRetrieval=history.some(event=>event.createdAt.getTime()<=now.getTime()-86400000);const transfer=item.question.cognitiveOperations.includes("apply")&&history.some(event=>typeof event.conditions.questionId==="string"&&event.conditions.questionId!==item.question.id);const conditions={policyVersion:MASTERY_V2,outcome:item.evaluation.outcome,difficulty:item.question.difficulty,mode:"assessment",hintLevel:0,solutionRevealed:false,questionId:item.question.id,questionVersion:item.question.version,delayedRetrieval,transfer,assessmentId:id};this.store.conceptEvidence.push({id:crypto.randomUUID(),ownerId,conceptStableId,attemptId,type:"assessment_result",strength:evidenceStrengthV2({correct:item.evaluation.correct,difficulty:item.question.difficulty,mode:"assessment",hintLevel:0,solutionRevealed:false,questionId:item.question.id,delayedRetrieval,transfer,createdAt:now}),sourceType:"assessment_attempt",sourceId:attemptId,conditions,createdAt:now});
        const review=this.store.reviewSchedules.find(item=>item.ownerId===ownerId&&item.conceptStableId===conceptStableId);if(review){review.nextReviewAt=new Date(now.getTime()+86400000);review.policyVersion=REVIEW_V2;}else this.store.reviewSchedules.push({ownerId,conceptStableId,currentMasteryState:item.evaluation.correct?"understood":"introduced",lastReviewedAt:null,nextReviewAt:new Date(now.getTime()+86400000),reviewCount:0,recentQuality:item.evaluation.correct?3:1,policyVersion:REVIEW_V2,updatedAt:now,metadata:{stage:0,stabilityDays:1}});
      }
    }
    row.result={correct:scored.correct,scored:scored.scored,total:scored.total,bySubject:scored.bySubject,diagnostic:diagnosticSignals(scored.items),policyVersion:ASSESSMENT_POLICY,finishedAfterDeadline:now.getTime()>row.deadlineAt.getTime(),items:scored.items.map(item=>({versionId:item.versionId,questionId:item.question.id,...assessmentFeedback(item.question,item.evaluation.outcome),outcome:item.evaluation.outcome,explanation:item.question.explanation,conceptIds:item.question.conceptIds}))};row.status="FINALIZED";row.finalizedAt=now;return row.result;
  }
}
