import { describe, expect, it } from "vitest";
import { eq } from "drizzle-orm";
import source from "../../packs/seeds/ifsc-2027.golden.track.v2.json";
import { importTrackPack } from "@/features/import/api";
import { DrizzleTrackImportRepository } from "@/db/repositories/track-import-repository";
import { MemoryTrackImportRepository, getMemoryStore } from "@/db/repositories/memory-store";
import { LessonResumeRepository } from "@/db/repositories/lesson-resume-repository";
import { MemoryLessonResumeRepository } from "@/db/repositories/memory-lesson-resume-repository";
import { StudySessionRepository } from "@/db/repositories/study-session-repository";
import { MemoryStudySessionRepository } from "@/db/repositories/memory-study-session-repository";
import { CatalogRepository } from "@/db/repositories/catalog-repository";
import { MemoryCatalogRepository } from "@/db/repositories/memory/catalog";
import { emptyResume } from "@/features/lessons/resume-contracts";
import { sessionItemsSchema } from "@/features/study-sessions/contracts";
import { attempts, conceptEvidence, lessons, questionVersions } from "@/db/schema";
import { createMigratedPgliteTestDatabase } from "./pglite-test-db";

describe.each(["memory", "sql"] as const)("lesson resume (%s)", kind => {
  it("isolates owners and scopes, preserves revisions, retries idempotently and never creates evidence", async () => {
    const database = kind === "sql" ? await createMigratedPgliteTestDatabase() : undefined;
    const store = structuredClone(getMemoryStore()); store.packImports = []; store.lessonResumes = []; store.studySessions = []; store.conceptEvidence = []; store.attempts = [];
    try {
      const fixture = structuredClone(source);
      fixture.questions.forEach(question => { question.status = "published"; question.exposurePolicy.minimumDaysBetween = 0; });
      fixture.track.modules.forEach(moduleRecord => moduleRecord.lessons.forEach(lesson => { lesson.status = "published"; }));
      expect((await importTrackPack(fixture, database ? new DrizzleTrackImportRepository(database.db) : new MemoryTrackImportRepository(store))).status).toBe("imported");
      if (database) for (const row of await database.db.select().from(lessons)) await database.db.update(lessons).set({ metadata: { ...row.metadata as object, status: "published", qaReleaseId: crypto.randomUUID() } }).where(eq(lessons.id, row.id));
      if (database) await database.db.update(questionVersions).set({ status: "published" });
      const catalog = database ? new CatalogRepository(database.db) : new MemoryCatalogRepository(store);
      const scope = (await catalog.getLesson("CIE-06"))!.resumeScope!;
      const repository = database ? new LessonResumeRepository(database.db) : new MemoryLessonResumeRepository(store);
      const input = { scope, revision: 0, mutationId: crypto.randomUUID(), data: { ...emptyResume(), stepId: "cie-06-q1", drafts: [{ activityId: "cie-06-q1", questionId: "Q-CIE-GOLDEN-1", questionVersion: 1, response: "A", submissionKey: crypto.randomUUID(), baseAttemptId: null }] } };
      expect(await repository.get("learner", scope)).toBeNull();
      const saved = await repository.save("learner", input);
      expect(saved.revision).toBe(1); expect(await repository.save("learner", input)).toEqual(saved);
      expect(await repository.get("other", scope)).toBeNull();
      await expect(repository.save("learner", { ...input, mutationId: crypto.randomUUID() })).rejects.toThrow("newer lesson resume");
      await expect(repository.save("learner", { ...input, data: { ...input.data, stepId: "changed" } })).rejects.toThrow("newer lesson resume");
      await expect(repository.save("learner", { ...input, revision: 1, mutationId: crypto.randomUUID(), data: { ...input.data, drafts: [{ ...input.data.drafts[0], questionId: "outside" }] } })).rejects.toThrow("resume unavailable");
      await expect(repository.get("learner", { ...scope, version: 999 })).rejects.toThrow("resume unavailable");
      expect((await repository.get("learner", scope))?.data).toEqual(input.data);
      const sessions = database ? new StudySessionRepository(database.db, false, true) : new MemoryStudySessionRepository(store, false, true);
      const session = (await sessions.plan("learner", 10))!; await sessions.transition("learner", session.id, "start");
      const item = sessionItemsSchema.parse(session.items)[0];
      const sessionScope = { trackId: item.trackId!, lessonId: item.lessonId, version: item.version, sessionId: session.id };
      const sessionInput = { scope: sessionScope, revision: 0, mutationId: crypto.randomUUID(), data: emptyResume() };
      expect((await repository.save("learner", sessionInput)).revision).toBe(1);
      await expect(repository.get("other", sessionScope)).rejects.toThrow("resume unavailable");
      await sessions.transition("learner", session.id, "complete");
      await expect(repository.save("learner", { ...sessionInput, revision: 1, mutationId: crypto.randomUUID() })).rejects.toThrow("resume unavailable");
      expect((await repository.get("learner", scope))?.data).toEqual(input.data);
      expect(database ? await database.db.select().from(attempts) : store.attempts).toHaveLength(0);
      expect(database ? await database.db.select().from(conceptEvidence) : store.conceptEvidence).toHaveLength(0);
      const newer = structuredClone(fixture); newer.version = fixture.version + 1;
      newer.track.modules.forEach(moduleRecord => moduleRecord.lessons.forEach(lesson => { lesson.version = 2; lesson.status = "draft"; }));
      const newImport = await importTrackPack(newer, database ? new DrizzleTrackImportRepository(database.db) : new MemoryTrackImportRepository(store));
      expect(newImport.status, JSON.stringify(newImport)).toBe("imported");
      expect((await catalog.getLesson("CIE-06"))?.resumeScope).toBeUndefined();
      expect((await repository.get("learner", scope))?.data).toEqual(input.data);
    } finally { await database?.close(); }
  });
});
