"use client";
import {useState} from "react";
import {z} from "zod";
const strings=z.array(z.string());
const assetPreview=z.object({kind:z.literal("assets"),images:z.array(z.object({id:z.string(),title:z.string(),type:z.string(),subjectCodes:strings,conceptIds:strings,tags:strings,altText:z.string(),licenseStatus:z.string(),verifiedAt:z.string().nullable(),exposure:z.string(),reusable:z.boolean(),interactiveReady:z.boolean(),reasons:strings,attribution:z.string()})),videos:z.number(),books:z.number(),caveats:strings});
const blueprintPreview=z.object({kind:z.literal("blueprint"),title:z.string(),reviewState:z.string(),confidence:z.number(),sourceMatches:z.boolean(),learningGoal:z.string().nullable(),blocks:strings,caveats:strings,reviewReasons:strings});
const normalized=(value:string)=>value.normalize("NFD").replace(/\p{Diacritic}/gu,"").toLocaleLowerCase("pt-BR");
export function AuthoringMetadataView({metadata}:{metadata:unknown}){
 const [query,setQuery]=useState(""),[reuseOnly,setReuseOnly]=useState(false),assets=assetPreview.safeParse(metadata),blueprint=blueprintPreview.safeParse(metadata);
 if(assets.success){const rows=assets.data.images.filter(asset=>(!reuseOnly||asset.reusable)&&normalized(`${asset.title} ${asset.id} ${asset.type} ${asset.subjectCodes.join(" ")} ${asset.conceptIds.join(" ")} ${asset.tags.join(" ")}`).includes(normalized(query)));
  return <section aria-label="Assets validados"><h3>Assets do arquivo de origem</h3>{assets.data.caveats.map(text=><p key={text}>{text}</p>)}<label className="learning-field">Buscar assets<input type="search" value={query} maxLength={160} onChange={e=>setQuery(e.target.value)}/></label><label className="learning-check"><input type="checkbox" checked={reuseOnly} onChange={e=>setReuseOnly(e.target.checked)}/>Somente reutilização elegível</label><p role="status">{rows.length} de {assets.data.images.length} imagens · {assets.data.videos} vídeos · {assets.data.books} livros.</p>{!rows.length?<p>Nenhum asset encontrado com estes filtros.</p>:<ul className="record-list">{rows.map(asset=><li key={asset.id}><h4>{asset.title}</h4><p>{asset.type} · {asset.id} · {asset.licenseStatus} · exposição {asset.exposure}</p><p>Reutilização: {asset.reusable?"elegível nos registros declarados":"indisponível"}. Interatividade: {asset.interactiveReady?"declarada":"não confirmada"}.</p><p>{asset.attribution}</p><p>Texto alternativo: {asset.altText}</p>{asset.subjectCodes.length>0&&<p>Áreas: {asset.subjectCodes.join(", ")}</p>}{asset.reasons.length>0&&<ul>{asset.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul>}</li>)}</ul>}</section>;
 }
 if(blueprint.success){const b=blueprint.data;return <section aria-label="Blueprint validado"><h3>{b.title}</h3><p>Estado declarado: {b.reviewState} · confiança da proposta: {Math.round(b.confidence*100)}%.</p><p>Vínculo com a versão/hash da fonte: {b.sourceMatches?"corresponde":"não confirmado"}.</p><h4>Objetivo de aprendizagem</h4><p>{b.learningGoal??"Objetivo original ausente; nenhuma declaração foi inventada."}</p><h4>Blocos propostos</h4><ul>{b.blocks.map(block=><li key={block}>{block}</li>)}</ul>{[...b.caveats,...b.reviewReasons].map((finding,index)=><p key={index}>{finding}</p>)}</section>;}
 return <p role="alert">A resposta de metadata não corresponde ao formato esperado. Tente carregar o arquivo novamente.</p>;
}
