"use client";
import { useState } from "react";
import Link from "next/link";
import { authoringBlockTypes,authoringContextSchema,buildAuthoringPacket,type AuthoringContext } from "./authoring-contracts";
import { lessonVersionPackSchema } from "@/features/import/application/lesson-version-contracts";
import { apiErrorSchema } from "@/lib/api-response";
import { AuthoringMetadataView } from "./authoring-metadata-view";

export function AuthoringWorkbench({initialLessonId=""}:{initialLessonId?:string}){
  const [lessonId,setLessonId]=useState(initialLessonId),[context,setContext]=useState<AuthoringContext|null>(null),[type,setType]=useState<typeof authoringBlockTypes[number]>("note"),[concept,setConcept]=useState(""),[content,setContent]=useState(""),[packet,setPacket]=useState(""),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[metadata,setMetadata]=useState<unknown>(null),[validated,setValidated]=useState(false),[imported,setImported]=useState(false);
  async function load(){setBusy(true);setStatus("");try{const r=await fetch(`/api/admin/authoring-context?lessonId=${encodeURIComponent(lessonId)}`);if(!r.ok)throw new Error("Esta aula não tem contexto publicado disponível.");const source=authoringContextSchema.parse(await r.json());setContext(source);setConcept(source.lesson.concepts[0]?.id??"");setPacket("");setValidated(false);setImported(false);setStatus("Fonte e hashes carregados. A versão publicada permanece preservada.");}catch(error){setStatus(error instanceof Error?error.message:"Falha ao carregar fonte.");}finally{setBusy(false);}}
  function add(){if(!context)return;try{const payload=type==="numeric-explorer"?JSON.parse(content):type==="code"?{type,language:"text",code:content}:{type,content};const block={id:`studio-${crypto.randomUUID()}`,type,schemaVersion:1,conceptIds:[concept],payload};const draft=buildAuthoringPacket(context,[block],`studio.${crypto.randomUUID()}`);setPacket(JSON.stringify(draft,null,2));setValidated(false);setImported(false);setStatus("Próxima versão preparada como rascunho. Faça a prévia antes de importar.");}catch{setStatus("Preencha o conteúdo no formato do bloco selecionado.");}}
  async function send(preview:boolean){setBusy(true);try{const parsed=lessonVersionPackSchema.parse(JSON.parse(packet));const r=await fetch(preview?"/api/import/lesson/preview":"/api/import/lesson",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(parsed)});const result=await r.json();if(!r.ok){const error=apiErrorSchema.safeParse(result);throw new Error(error.success?error.data.message??"A versão não passou pela validação.":"Falha de validação.");}if(preview)setValidated(true);else setImported(true);setStatus(preview?"Prévia validada. O rascunho pode ser importado.":"Rascunho importado. Abra a revisão administrativa para publicar pelo modo autorizado.");}catch(error){setStatus(error instanceof Error?error.message:"Falha ao preparar versão.");}finally{setBusy(false);}}
  async function inspect(kind:"blueprint"|"assets",file:File){setBusy(true);try{if(file.size>2_000_000)throw new Error("Arquivo excede 2 MB.");const data=JSON.parse(await file.text());const r=await fetch("/api/admin/authoring-metadata",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,data,lessonId:context?.lesson.id,version:context?.lesson.version})});const result=await r.json();if(!r.ok)throw new Error(result.message??"Metadata inválida.");setMetadata(result);setStatus("Metadata validada. As ressalvas de origem e revisão continuam visíveis.");}catch(error){setStatus(error instanceof Error?error.message:"Falha ao ler arquivo.");}finally{setBusy(false);}}
  return <div className="authoring-workbench"><section className="module-section"><h2>Fonte e saúde do conteúdo</h2><div className="learning-controls targeted-practice-controls"><label className="learning-field">ID da aula<input value={lessonId} onChange={e=>setLessonId(e.target.value)} disabled={busy}/></label><button type="button" className="secondary-action" disabled={busy||!lessonId} onClick={()=>void load()}>Carregar fonte</button></div>{context&&<><p>{context.lesson.title} · versão {context.lesson.version} · {context.published?"Publicada":"Origem ainda não publicada"}</p><ul>{context.findings.map(finding=><li key={finding}>{finding}</li>)}</ul><p>{context.lesson.blocks.length} blocos · {context.lesson.activities.length} atividades · {context.questionReferences.length} referências de questões preservadas</p><Link href={`/admin/review/${encodeURIComponent(context.lesson.id)}?version=${context.lesson.version}`}>Ver modo e auditoria de publicação</Link></>}</section>
    {context&&<section className="module-section"><h2>Adicionar bloco na próxima versão</h2><p>O rascunho retém todos os blocos, campos e questões de origem.</p><div className="mistake-reflection-form learning-controls"><label className="learning-field">Tipo de bloco<select value={type} onChange={e=>setType(e.target.value as typeof type)}>{authoringBlockTypes.map(value=><option key={value} value={value}>{value}</option>)}</select></label><label className="learning-field">Conceito de origem<select value={concept} onChange={e=>setConcept(e.target.value)}>{context.lesson.concepts.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label className="learning-field">Conteúdo do bloco<textarea value={content} onChange={e=>setContent(e.target.value)} maxLength={12000}/></label><button type="button" className="secondary-action" disabled={busy||!content||!context.published} onClick={add}>Preparar rascunho</button></div>{packet&&<><details><summary>Pacote da nova versão</summary><label className="learning-field">JSON do rascunho<textarea value={packet} onChange={e=>{setPacket(e.target.value);setValidated(false);}} rows={12}/></label></details><div className="learning-controls"><button type="button" className="secondary-action" disabled={busy} onClick={()=>void send(true)}>Validar prévia</button><button type="button" className="primary-button" disabled={busy||!validated} onClick={()=>void send(false)}>Importar rascunho</button><Link href={`/admin/review/${encodeURIComponent(context.lesson.id)}?version=${context.lesson.version+1}`}>Abrir nova versão para publicar</Link></div><div className="authoring-mobile-preview"><iframe title={imported?"Prévia móvel do rascunho":"Prévia móvel da fonte"} src={`/lessons/${encodeURIComponent(context.lesson.id)}?version=${context.lesson.version+(imported?1:0)}`} loading="lazy"/></div></>}</section>}
    <section className="module-section"><h2>Biblioteca de assets e Blueprint Viewer</h2><p>Selecione metadata exportada pelo Studio. O painel mostra elegibilidade e ressalvas; não cria aprovação editorial ou de licença.</p><label className="learning-field">Media pack de assets<input type="file" accept="application/json,.json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void inspect("assets",file);}}/></label><label className="learning-field">Lesson blueprint<input type="file" accept="application/json,.json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void inspect("blueprint",file);}}/></label>{metadata!==null&&<AuthoringMetadataView metadata={metadata}/>}</section>
    {status&&<p role="status">{status}</p>}
  </div>;
}
