"use client";
import { assessmentFinalizedResponseSchema, assessmentSavedResponseSchema, readValidatedResponse } from "@/lib/api-response";
import { Paragraphs } from "@/components/ui/paragraphs";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import type { AssessmentView } from "./api";
import { initialResponse,ResponseFields,type QuestionResponse } from "@/features/activities/components/response-fields";
import { QuestionAssets } from "@/features/questions/question-assets";
type QuestionState={dirty:boolean;saving:boolean;answered:boolean;flagged:boolean};
const answered=(value:unknown)=>typeof value==="string"?value.trim().length>0:Array.isArray(value)?value.length>0:typeof value==="object"&&value!==null?Object.values(value).some(item=>typeof item==="string"&&item.length>0):false;
export function AssessmentPanel({view,serverNow,enhanced=false}:{view:AssessmentView;serverNow:number;enhanced?:boolean}){
  const router=useRouter(),[now,setNow]=useState(serverNow),[busy,setBusy]=useState(false),[error,setError]=useState(""),[selected,setSelected]=useState(0),[review,setReview]=useState(false);
  const [states,setStates]=useState<Record<string,QuestionState>>(()=>Object.fromEntries(view.questions.map(item=>{const response=view.responses.find(row=>row.versionId===item.versionId);return[item.versionId,{dirty:false,saving:false,answered:answered(response?.response),flagged:response?.flagged??false}];})));
  useEffect(()=>{const start=performance.now();const timer=setInterval(()=>setNow(serverNow+performance.now()-start),1000);return()=>clearInterval(timer);},[serverNow]);
  const remaining=Math.max(0,Math.ceil((Date.parse(view.deadlineAt)-now)/1000)),active=view.status==="ACTIVE"&&remaining>0;
  const pending=Object.values(states).some(state=>state.dirty||state.saving);
  const savedCount=Object.values(states).filter(state=>state.answered).length,flaggedCount=Object.values(states).filter(state=>state.flagged).length;
  async function finish(){setBusy(true);setError("");try{const response=await fetch(`/api/assessments/${view.id}/finalize`,{method:"POST"});if(!response.ok)throw new Error("Não foi possível finalizar. As respostas salvas foram preservadas; tente novamente.");await readValidatedResponse(response,assessmentFinalizedResponseSchema);router.refresh();}catch(error){setError(error instanceof Error?error.message:"Falha ao finalizar.");}finally{setBusy(false);}}
  const hh=String(Math.floor(remaining/3600)),mm=String(Math.floor(remaining%3600/60)).padStart(2,"0"),ss=String(remaining%60).padStart(2,"0");
  const navigate=(index:number)=>{setSelected(index);setReview(false);};
  return <div className="assessment-run">
    <div className="exam-timer" data-low={remaining<600} role="timer" aria-label="Tempo restante"><span>Tempo restante</span><strong>{hh}:{mm}:{ss}</strong><small>{view.questions.length} questões</small></div>
    <p className="assessment-note">Salve cada resposta. Dá para mudar até finalizar; o resultado aparece no fim.</p>
    {!active&&view.status==="ACTIVE"&&<p className="assessment-alert" role="alert">Tempo encerrado. Finalize para ver o resultado das respostas salvas.</p>}
    {enhanced&&<nav className="exam-navigation" aria-label="Navegação das questões">{view.questions.map((item,index)=>{const state=states[item.versionId];return <button type="button" key={item.versionId} className="secondary-action" aria-label={`Questão ${index+1}, ${state?.dirty?"alterada, não salva":state?.answered?"resposta salva":"sem resposta"}${state?.flagged?", marcada para revisar":""}`} aria-current={!review&&selected===index?"step":undefined} data-saved={state?.answered&&!state.dirty} data-flagged={state?.flagged} onClick={()=>navigate(index)}>{index+1}{state?.flagged&&<span aria-hidden="true"> · Revisar</span>}</button>;})}</nav>}
    {enhanced&&review&&<section className="exam-final-review" aria-label="Conferência final"><h2>Confira antes de finalizar</h2><p>{savedCount} {savedCount===1?"resposta salva":"respostas salvas"} · {flaggedCount} {flaggedCount===1?"questão marcada":"questões marcadas"} para revisar.</p>{pending&&<p role="alert">Há alterações ou salvamentos pendentes. Volte à questão e salve antes de finalizar.</p>}<ol>{view.questions.map((item,index)=><li key={item.versionId}><button type="button" className="secondary-action" onClick={()=>navigate(index)}>Ver questão {index+1}</button> · {states[item.versionId]?.dirty?"Alterada, não salva":states[item.versionId]?.answered?"Resposta salva":"Sem resposta"}{states[item.versionId]?.flagged?" · Revisar":""}</li>)}</ol></section>}
    {view.questions.map((item,index)=><div key={item.versionId} hidden={enhanced&&(review||selected!==index)}><AssessmentQuestion item={item} initial={view.responses.find(response=>response.versionId===item.versionId)} assessmentId={view.id} index={index} disabled={!active||busy} onState={value=>setStates(current=>({...current,[item.versionId]:value}))}/></div>)}
    {enhanced&&!review&&<div className="learning-controls exam-step-controls"><button type="button" className="secondary-action" disabled={selected===0} onClick={()=>navigate(selected-1)}>Questão anterior</button><span>Questão {selected+1} de {view.questions.length}</span><button type="button" className="secondary-action" disabled={selected===view.questions.length-1} onClick={()=>navigate(selected+1)}>Próxima questão</button><button type="button" className="primary-button" onClick={()=>setReview(true)}>Conferir simulado</button></div>}
    <footer className="session-finish"><p>{pending&&active?"Salve as respostas alteradas antes de finalizar.":"Revisou tudo? Finalize para ver seu resultado."}</p>{(!enhanced||review||!active)&&<button type="button" className="primary-button" disabled={busy||active&&pending} onClick={()=>void finish()}>{busy?"Finalizando…":"Finalizar simulado"}</button>}{error&&<p role="alert">{error}</p>}</footer>
  </div>;
}
function AssessmentQuestion({item,initial,assessmentId,index,disabled,onState}:{item:AssessmentView["questions"][number];initial?:AssessmentView["responses"][number];assessmentId:string;index:number;disabled:boolean;onState:(state:QuestionState)=>void}){
  const [response,setResponse]=useState<QuestionResponse>(()=>initial?.response===undefined?initialResponse(item.question):initial.response as QuestionResponse),[flagged,setFlagged]=useState(initial?.flagged??false),[busy,setBusy]=useState(false),[status,setStatus]=useState(initial?"Resposta salva":"");
  const id=`assessment-${item.versionId}`;
  function change(value:QuestionResponse,nextFlag=flagged){setResponse(value);setFlagged(nextFlag);setStatus("Resposta alterada; salve para registrar.");onState({dirty:true,saving:false,answered:false,flagged:nextFlag});}
  return <section className="learning-interaction exam-question" data-flagged={flagged} aria-labelledby={`${id}-title`}><span className="question-number" aria-hidden="true">{index+1}</span>{item.question.stimulus&&<div className="question-stimulus"><Paragraphs text={item.question.stimulus}/></div>}<h2 id={`${id}-title`}><span className="visually-hidden">Questão {index+1}. </span>{item.question.stem}</h2><QuestionAssets assets={item.question.assets}/><form onSubmit={async event=>{event.preventDefault();setBusy(true);onState({dirty:true,saving:true,answered:false,flagged});try{const result=await fetch(`/api/assessments/${assessmentId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({questionVersionId:item.versionId,response,flagged})});if(!result.ok)throw new Error();await readValidatedResponse(result,assessmentSavedResponseSchema);setStatus("Resposta salva");onState({dirty:false,saving:false,answered:answered(response),flagged});}catch{setStatus("Resposta ainda não salva. Confira a conexão e tente novamente.");onState({dirty:true,saving:false,answered:false,flagged});}finally{setBusy(false);}}}><ResponseFields question={item.question} id={id} response={response} disabled={disabled||busy} onChange={value=>change(value)}/><label className="flag-toggle"><input type="checkbox" checked={flagged} disabled={disabled||busy} onChange={event=>change(response,event.target.checked)}/>Revisar depois</label><button className="primary-button" disabled={disabled||busy} type="submit">{busy?"Salvando…":"Salvar resposta"}</button><p className="save-status" role="status" data-saved={status==="Resposta salva"}>{status}</p></form></section>;
}
